# Generated by Django 4.1.3 on 2022-11-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('tags', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('APPROVED', 'Approved'), ('DELIVERED', 'Delivered')], max_length=20, verbose_name='Status')),
            ],
        ),
    ]
